title: Data Story
description: We're shining bright
theme: just-the-docs

url: https://thetayne.github.io/adadocs

color_scheme: foo

footer_content: "EPFL©2023 CS-401 | Project made by Emma, Marine, Tim Bächle, Felix Rodriguez and Tim Wiebelhaus"
